### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by Flyerison** [gaojunle/aliyun-sms-nodejs#1]
SyntaxError: Unexpected identifier
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

这个是什么原因呢？

**Comment by gaojunle** [comment]
看提示是语法错误，在vm.js的74行10列，请查一下；
